import requests
import os
import time


sounds = [
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/a.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/b.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/c.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/d.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/e.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/f.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/g.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/h.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/i.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/j.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/k.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/l.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/m.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/n.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/o.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/p.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/qu.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/r.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/s.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/t.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/u.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/v.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/w.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/x.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/y.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/z.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ch.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ck.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/dge.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/gn.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/kn.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ng.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/nk.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ph.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/sh.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/tch.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/th.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/wh.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/wr.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ai.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/au.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/aw.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ay.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ea.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ee.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ei.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/eigh.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ew.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ey.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ie.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/igh.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/oa.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/oe.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/oi.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/oo.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ou.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ough.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ow.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/oy.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ui.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/er.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ir.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ur.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/or_Sound.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ear.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/our.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ci.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/si.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ti.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/sh.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ed.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/ar.mp3",
    "https://apps.allaboutlearningpress.com/Release_Web-v1.0/sounds/or.mp3",
]
for sound_url in sounds:
    r = requests.get(sound_url)  # create HTTP response object
    file_path = os.path.join("sounds", os.path.basename(sound_url))
    with open(file_path, "wb") as f:
        # to a new file in binary mode.
        f.write(r.content)
        print("Downloaded: {0}".format(file_path))
        time.sleep(0.5)